# Generated by Django 4.2.11 on 2025-11-19 15:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Идентификатор запроса для идемпотентности",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("to_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("to_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("to_telegram_chat_id", models.CharField(blank=True, max_length=100, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField()),
                (
                    "channels",
                    models.JSONField(
                        default=list,
                        help_text='Список каналов в порядке приоритета, например: ["email", "sms", "telegram"]',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "used_channel",
                    models.CharField(
                        blank=True,
                        help_text="Канал, через который успешно доставлено уведомление",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="notificatio_status_d92267_idx"),
                    models.Index(fields=["request_id"], name="notificatio_request_41e337_idx"),
                    models.Index(fields=["created_at"], name="notificatio_created_46ad24_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("telegram", "Telegram")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")], max_length=20
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "ordering": ["attempted_at"],
                "indexes": [
                    models.Index(
                        fields=["notification", "attempted_at"],
                        name="notificatio_notific_c00beb_idx",
                    ),
                    models.Index(
                        fields=["channel", "status"], name="notificatio_channel_870dc5_idx"
                    ),
                ],
            },
        ),
    ]
